version: '3'
services:
  movies:
    image: durgaprasad9346/new1:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: durgaprasad9346/fb:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: durgaprasad9346/new:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
