version: '3'
services:
  movies:
    image: durgaprasad9346/facebook
    ports:
      - "86:80"
    deploy:
      replicas: 3

  train:
    image: durgaprasad9346/insta:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3

  dth:
    image: durgaprasad9346/whatsapp:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
